lexer grammar JulayLexer;

COMMA : ',' ;
DOT : '.' ;
COLON : ':' ;
LPAREN : '(' ;
RPAREN : ')' ;
LBRACK : '[' ;
RBRACK : ']' ;
LCURLY : '{' ;
RCURLY : '}' ;
PARALLEL : '||' ;

TRUE : 'true' ;
FALSE : 'false' ;
AND : '&' ;
MODELS : '|=' ;
OR : '|' ;
NOT : '~' ;
TIMES : '*' ;
DIV : '/' ;
MOD : '%' ;
PLUS : '+' ;
MINUS : '-' ;
LT : '<' ;
LTE : '<=' ;
GT : '>' ;
GTE : '>=' ;
EQ : '=' ;
NEQ : '~=' ;
NIN : '~in' ;
ASGN_EQ : ':=' ;
IMPLIES : '=>' ;
IFF : '<=>' ;
IF : 'if' ;
ELSE : 'else' ;
LET : 'let' ;
WHEN : 'when' ;
IN : 'in' ;
TO : 'to' ;
ARROW : '->' ;
IMPORT : 'import' ;
EXPORT : 'export' ;
LISTOF : 'listOf' ;
SETOF : 'setOf' ;
MAPOF : 'mapOf' ;


OBJ : 'obj' ;
SORT : 'sort' ;
PROC : 'proc' ;
API : 'api' ;
CALLS : 'calls' ;
COMPILE : 'compile' ;
SPEC : 'spec' ;
INVARIANT : 'invariant' ;
FORALL : 'forall' ;
EXISTS : 'exists' ;
VAR : 'var' ;
CONST : 'const' ;
CONSTRUCTOR : 'constructor' ;
TRANSITION : 'transition' ;
INTERNAL : 'internal' ;
PROVIDER : 'provider' ;
CLIENT : 'client' ;
SESSION : 'session' ;
GUARD : 'guard' ;
TRANSIT : 'transit' ;
ERROR : 'error' ;
BEFORE : 'before' ;
AFTER : 'after' ;
FUN : 'fun' ;
PROCFUN : 'procfun' ;
RETURN : 'return' ;
ALSO : 'also' ;
WITH : 'with' ;
THIS : 'this' ;

REAL : [-]?[0-9]+ '.' [0-9]+ ;
INT : [-]?[0-9]+ ;
ID: [a-zA-Z_][a-zA-Z_0-9]* ;
STRING: '"' ~["]* '"' ;

WS           : [ \t\r\n\u000C]+ -> channel(HIDDEN);
COMMENT      : '/*' .*? '*/'    -> channel(HIDDEN);
LINE_COMMENT : '//' ~[\r\n]*    -> channel(HIDDEN);
